[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
synthetic_sc = "ChoFqza3aBg3s7a2gdzHz9YNizfe7phZKnjh5nz8pKHg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
